# Simple workflow for deploying static content to GitHub Pages
name: BuildPage

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '18'


      - name: Chache dependencies
        uses: actions/chache@v3
        id: npm-chache
        with:
          # Upload entire repository
          path: |
            ~/.npm
            **/node_node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
           ${{ runner.os }}-npm-cache-

       # 安装依赖 npm
      - name: Install dependencies
        # 如果没有命中缓存才执行 npm install
        if: steps.npm-cache.outputs['restore-keys'] == ''
        run: npm install
      # 运行构建脚本
      - name: Run Build Script
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
        # env:
          # 部署到 FrontPages 分支
          # BRANCH: FrontPages
          # 部署目录为 VuePress 的默认输出目录
          FOLDER: docs/.vuepress/dist
          # 当前仓库的密钥
          SSH_PRIVATE_KEY: "${{ secrets.DEPLOY_PRIVATE_KEY }}"
